bdd: #Migration automatique
	$(MAKE) oui
	$(MAKE) doctrine
.PHONY: bdd
	

oui: #Migration automatique
	php bin/console doctrine:schema:update --force
   
.PHONY: oui
	

doctrine: #ça lance les fixtures
	 php bin/console doctrine:fixtures:load
.PHONY: doctrine


addGit: #ça envoie un push tout seul
	git add --all
	git commit -m ""
	git push

updateGit: #ça actualise ta branche actuel avec le main
	git fetch origin main
	git merge origin/main

	